export const  LANG_LOG_KEY="DAIRY_SENSE_LANG"
export const  FARM_STATUS_LOG="FARM_STATUS_LOG"
export const FARM_STATUS_UPDATE_SUCCESS="[FARM_STATUS_UPDATE_SUCCESS]"
export const FARM_STATUS_UPDATE_FAILED="[FARM_STATUS_UPDATE_FAILED]"

export const FARMS_EXPORT_SUCCESS="[FARMS_EXPORT_SUCCESS]"
export const FARMS_EXPORT_FAILED="[FARMS_EXPORT_FAILED]"
